const CONSTANTS = {
  content: {
    SPACEX_LAUNCH_PROGRAMS: "SpaceX Launch Programs",
    LOADING: "Loading...",
    NO_DATA_AVAILABLE: "No Data Available",
    COPYRIGHT: "Developed by Vratika Goel",
    MISSION_PATCH_ALT: "Misson Patch",
    HASH: "#",
    MISSION_IDS: "Mission Ids:",
    LAUNCH_YEAR: "Launch Year:",
    SUCCESSFUL_LAUNCH: "Successful Launch:",
    SUCCESSFUL_LAND: "Successful Landing:",
    FILTERS: "Filters",
    LAUNCH_YEAR_HEADING: "Launch Year",
    SUCCESSFUL_LAUNCH_HEADING: "Successful Launch",
    SUCCESSFUL_LAND_HEADING: "Successful Landing",
    LAUNCH_YEAR_ID: "launch_year",
    SUCCESSFUL_LAUNCH_ID: "launch_success",
    SUCCESSFUL_LAND_ID: "land_success",
  },
  BASE_URL: 'https://api.spaceXdata.com/v3/launches?limit=100',
  BOOLEAN_ARR: ["true", "false"],
  LAUNCH_YEAR_ARR: [
    "2006",
    "2007",
    "2008",
    "2009",
    "2010",
    "2011",
    "2012",
    "2013",
    "2014",
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
  ],
};

module.exports = { CONSTANTS };
